import { Partner, Project, BOQItem, CostExpense, Worker, Vendor, PurchaseOrder, PaymentTermin, SitePhoto, DailyReport } from './types';

export const initialPartners: Partner[] = [
  {
    id: 'pt-001',
    name: 'Arkana Design Studio',
    type: 'Arsitek / Konsultan',
    contactPerson: 'Ar. Danang Wicaksono, IAI',
    phone: '0812-8899-2311',
    email: 'danang@arkanadesign.co.id',
    address: 'Jl. Wijaya II No. 45, Kebayoran Baru, Jakarta Selatan',
    totalProjects: 4,
    activeProjects: 2,
    totalContractValue: 2270000000,
    paymentScore: 'Sangat Baik',
    notes: 'Partner arsitek premium dengan spesifikasi HPL Aica & lighting Flos. Selalu repeat client.',
  },
  {
    id: 'pt-002',
    name: 'Tanamera Hospitality Group',
    type: 'F&B Holding',
    contactPerson: 'Jessica Renata (Head of Expansion)',
    phone: '0811-9234-8800',
    email: 'jessica.r@tanameragroup.com',
    address: 'Gedung Graha Niaga Lt. 12, SCBD, Jakarta',
    totalProjects: 3,
    activeProjects: 1,
    totalContractValue: 1940000000,
    paymentScore: 'Baik',
    notes: 'Klien komersial retail. Termin pembayaran disiplin 14 hari kerja setelah BAST.',
  },
  {
    id: 'pt-003',
    name: 'PT Nexus Finansial Digital',
    type: 'Corporate Client',
    contactPerson: 'Bambang Trihatmojo (VP General Affairs)',
    phone: '0813-7722-1090',
    email: 'bambang.t@nexusfin.id',
    address: 'Treasury Tower Lt. 24, SCBD Sudirman, Jakarta Selatan',
    totalProjects: 2,
    activeProjects: 1,
    totalContractValue: 2150000000,
    paymentScore: 'Sangat Baik',
    notes: 'Perusahaan fintech tier 1. Butuh standar acoustic tinggi dan integrasi smart meeting room.',
  },
  {
    id: 'pt-004',
    name: 'PT Mega Citra Propertindo',
    type: 'Property Developer',
    contactPerson: 'Hendrik Setiawan (Project Director)',
    phone: '0818-4455-9011',
    email: 'hendrik.s@megacitra.com',
    address: 'Pakuwon Tower Lt. 18, Casablanca, Jakarta Selatan',
    totalProjects: 5,
    activeProjects: 1,
    totalContractValue: 3450000000,
    paymentScore: 'Perlu Follow-up',
    notes: 'Developer apartemen & mixed-use. Retensi 10% sering membutuhkan pengecekan ekstra.',
  },
];

export const initialProjects: Project[] = [
  {
    id: 'prj-001',
    code: 'SRA-2026-01',
    name: 'Fit-out Kantor FinTech Nexus SCBD',
    partnerId: 'pt-003',
    partnerName: 'PT Nexus Finansial Digital',
    endUser: 'Nexus FinTech Headquarters',
    projectType: 'Kantor B2B',
    location: 'Treasury Tower Lt. 24, SCBD, Jakarta Selatan',
    contractValue: 1450000000,
    hppBudget: 1015000000,
    actualCost: 938500000,
    targetMargin: 30,
    progress: 74,
    status: 'On-Site Fit-out',
    health: 'On Track',
    picProduksi: 'Budi Santoso (Kepala Produksi)',
    picLapangan: 'Rian Pratama (Site Supervisor)',
    startDate: '2026-08-01',
    targetCompletion: '2026-10-15',
    image: '/images/project-office.jpg',
    description: 'Pekerjaan fit-out kantor corporate seluas 480 m2 meliputi partisi kaca frameless curved, acoustic ceiling baffle, open workspace, board room, dan custom pantry cabinetry.',
    milestones: [
      { id: 'm1', title: 'Site Survey & Approval Drawing 3D', startDate: '2026-08-01', endDate: '2026-08-08', progress: 100, status: 'Selesai', weight: 10 },
      { id: 'm2', title: 'Demolisi & Pekerjaan Rangka Gypsum', startDate: '2026-08-09', endDate: '2026-08-22', progress: 100, status: 'Selesai', weight: 20 },
      { id: 'm3', title: 'Instalasi MEP & Jalur Kabel Data Server', startDate: '2026-08-23', endDate: '2026-09-05', progress: 100, status: 'Selesai', weight: 20 },
      { id: 'm4', title: 'Pabrikasi Custom Cabinets di Workshop', startDate: '2026-08-20', endDate: '2026-09-18', progress: 95, status: 'Sedang Berjalan', weight: 25 },
      { id: 'm5', title: 'Pemasangan Glass Partition & Wall Fluted Panel', startDate: '2026-09-15', endDate: '2026-10-02', progress: 65, status: 'Sedang Berjalan', weight: 15 },
      { id: 'm6', title: 'Finishing Touch, Deep Cleaning & BAST Retensi', startDate: '2026-10-03', endDate: '2026-10-15', progress: 0, status: 'Belum Mulai', weight: 10 },
    ],
  },
  {
    id: 'prj-002',
    code: 'SRA-2026-02',
    name: 'Tanamera Cafe & Roastery Senopati',
    partnerId: 'pt-002',
    partnerName: 'Tanamera Hospitality Group',
    endUser: 'Tanamera Senopati Store',
    projectType: 'F&B Cafe & Resto',
    location: 'Jl. Senopati No. 78, Kebayoran Baru, Jakarta Selatan',
    contractValue: 820000000,
    hppBudget: 574000000,
    actualCost: 568400000,
    targetMargin: 30,
    progress: 92,
    status: 'Finishing & QC',
    health: 'Perlu Perhatian',
    picProduksi: 'Budi Santoso (Kepala Produksi)',
    picLapangan: 'Hendra Gunawan (Site Supervisor)',
    startDate: '2026-07-15',
    targetCompletion: '2026-10-02',
    image: '/images/project-cafe.jpg',
    description: 'Renovasi interior cafe 180 m2 dengan signature curved ribbed oak bar counter, brass shelving, custom marble top, dan ambient lighting system.',
    milestones: [
      { id: 'm21', title: 'SIPIL & Waterproofing Bar Area', startDate: '2026-07-15', endDate: '2026-07-28', progress: 100, status: 'Selesai', weight: 20 },
      { id: 'm22', title: 'MEP Barista Plumbing & Daya Listrik 3 Phase', startDate: '2026-07-29', endDate: '2026-08-14', progress: 100, status: 'Selesai', weight: 25 },
      { id: 'm23', title: 'Pabrikasi Bar Counter Fluted Oak di Workshop', startDate: '2026-08-10', endDate: '2026-09-05', progress: 100, status: 'Selesai', weight: 30 },
      { id: 'm24', title: 'Instalasi Marmer Carrara & Brass Lighting', startDate: '2026-09-06', endDate: '2026-09-24', progress: 100, status: 'Selesai', weight: 15 },
      { id: 'm25', title: 'QC Barista Flow, Touchup Cat & Handover', startDate: '2026-09-25', endDate: '2026-10-02', progress: 60, status: 'Sedang Berjalan', weight: 10 },
    ],
  },
  {
    id: 'prj-003',
    code: 'SRA-2026-03',
    name: 'Penthouse Kemang Village Residence',
    partnerId: 'pt-001',
    partnerName: 'Arkana Design Studio',
    endUser: 'Private Residence (Mr. Ronald)',
    projectType: 'Luxury Residential',
    location: 'Tower Infinity Lt. 36, Kemang Village, Jakarta Selatan',
    contractValue: 1880000000,
    hppBudget: 1280000000,
    actualCost: 595000000,
    targetMargin: 31.9,
    progress: 46,
    status: 'Persiapan Workshop',
    health: 'On Track',
    picProduksi: 'Agus Salim (Workshop Manager)',
    picLapangan: 'Rian Pratama (Site Supervisor)',
    startDate: '2026-08-15',
    targetCompletion: '2026-11-30',
    image: '/images/project-workshop.jpg',
    description: 'Full interior luxury penthouse 320 m2. Walk-in closet dengan sistem sensor Blum, master bedroom fluted walnut, dapur gourmet island quartz slab, dan smart lighting KNX.',
    milestones: [
      { id: 'm31', title: 'As-Built Drawing & Laser 3D Scanning', startDate: '2026-08-15', endDate: '2026-08-25', progress: 100, status: 'Selesai', weight: 15 },
      { id: 'm32', title: 'Demolisi Plafon Lama & Relokasi Chiller AC', startDate: '2026-08-26', endDate: '2026-09-12', progress: 100, status: 'Selesai', weight: 20 },
      { id: 'm33', title: 'Produksi Kayu Solid & Veneer Walnut Workshop', startDate: '2026-09-05', endDate: '2026-10-20', progress: 50, status: 'Sedang Berjalan', weight: 35 },
      { id: 'm34', title: 'Instalasi Panel Dinding & Hidden Door', startDate: '2026-10-21', endDate: '2026-11-10', progress: 0, status: 'Belum Mulai', weight: 20 },
      { id: 'm35', title: 'QC Akhir, Furnishing & Serah Terima BAST', startDate: '2026-11-11', endDate: '2026-11-30', progress: 0, status: 'Belum Mulai', weight: 10 },
    ],
  },
  {
    id: 'prj-004',
    code: 'SRA-2026-04',
    name: 'Boutique Flagship Store PIK Avenue',
    partnerId: 'pt-004',
    partnerName: 'PT Mega Citra Propertindo',
    endUser: 'Lumière Fashion Flagship',
    projectType: 'Retail Boutique',
    location: 'PIK Avenue Mall Lt. GF-22, Jakarta Utara',
    contractValue: 720000000,
    hppBudget: 504000000,
    actualCost: 112000000,
    targetMargin: 30,
    progress: 20,
    status: 'Deal & SPK',
    health: 'On Track',
    picProduksi: 'Budi Santoso (Kepala Produksi)',
    picLapangan: 'Hendra Gunawan (Site Supervisor)',
    startDate: '2026-09-10',
    targetCompletion: '2026-11-10',
    image: '/images/project-office.jpg',
    description: 'Fit-out retail tenant mall 120 m2 dengan lighting CRI 95+, display island microcement, fitting room velvet acoustics, dan stainless hairline facade.',
    milestones: [
      { id: 'm41', title: 'SPK & Izin Kerja Mall Fit-out Permit', startDate: '2026-09-10', endDate: '2026-09-18', progress: 100, status: 'Selesai', weight: 20 },
      { id: 'm42', title: 'Pengadaan Material Stainless & Display Microcement', startDate: '2026-09-19', endDate: '2026-10-05', progress: 40, status: 'Sedang Berjalan', weight: 30 },
      { id: 'm43', title: 'Kerja Malam Mall: Pemasangan Partisi & Flooring', startDate: '2026-10-06', endDate: '2026-10-25', progress: 0, status: 'Belum Mulai', weight: 30 },
      { id: 'm44', title: 'Signage, Glass Shopfront & Opening Trial', startDate: '2026-10-26', endDate: '2026-11-10', progress: 0, status: 'Belum Mulai', weight: 20 },
    ],
  }
];

export const initialBOQItems: BOQItem[] = [
  // Material & Hardware
  {
    id: 'boq-01',
    category: 'Material & Hardware',
    itemDescription: 'Multipleks 18mm Uty (Bahan Dasar Cabinet)',
    specification: 'Plywood Uty Palm Grade AA 1220x2440x18mm',
    unit: 'Lembar',
    volume: 120,
    unitPriceHPP: 285000,
    totalHPP: 34200000,
    markupPercent: 35,
    quotationPrice: 46170000,
  },
  {
    id: 'boq-02',
    category: 'Material & Hardware',
    itemDescription: 'HPL Taco Woodgrain & Solid Matte Series',
    specification: 'Taco HPL TH-882J Warm Walnut & TH-001G Warm White',
    unit: 'Lembar',
    volume: 85,
    unitPriceHPP: 215000,
    totalHPP: 18275000,
    markupPercent: 35,
    quotationPrice: 24671250,
  },
  {
    id: 'boq-03',
    category: 'Material & Hardware',
    itemDescription: 'Hardware Blum Soft-Close Hinges & Runners',
    specification: 'Blum Clip Top Blumotion 110 deg + Tandembox antaro',
    unit: 'Set',
    volume: 64,
    unitPriceHPP: 145000,
    totalHPP: 9280000,
    markupPercent: 30,
    quotationPrice: 12064000,
  },
  {
    id: 'boq-04',
    category: 'Material & Hardware',
    itemDescription: 'Lem Kuning Aica Aibon Special Joinery',
    specification: 'Kaleng 2.5kg formula anti bau',
    unit: 'Kaleng',
    volume: 24,
    unitPriceHPP: 165000,
    totalHPP: 3960000,
    markupPercent: 25,
    quotationPrice: 4950000,
  },
  // Tenaga Kerja
  {
    id: 'boq-05',
    category: 'Tenaga Kerja',
    itemDescription: 'Upah Tukang Kayu Halus & HPL Workshop',
    specification: 'Borongan pembuatan custom cabinetry & fitting (5 Tukang x 26 Hari)',
    unit: 'Hari/Org',
    volume: 130,
    unitPriceHPP: 220000,
    totalHPP: 28600000,
    markupPercent: 30,
    quotationPrice: 37180000,
  },
  {
    id: 'boq-06',
    category: 'Tenaga Kerja',
    itemDescription: 'Upah Tukang Finishing Duco & Melamic Polyurethane',
    specification: 'Finishing semprot PU matte outdoor & interior (3 Tukang x 18 Hari)',
    unit: 'Hari/Org',
    volume: 54,
    unitPriceHPP: 240000,
    totalHPP: 12960000,
    markupPercent: 30,
    quotationPrice: 16848000,
  },
  {
    id: 'boq-07',
    category: 'Tenaga Kerja',
    itemDescription: 'Upah Setting Lapangan & Teknisi Instalasi On-Site',
    specification: 'Fitting on-site, levelling, MEP connection (4 Orang x 14 Hari)',
    unit: 'Hari/Org',
    volume: 56,
    unitPriceHPP: 200000,
    totalHPP: 11200000,
    markupPercent: 30,
    quotationPrice: 14560000,
  },
  // Subkontraktor Spesialis
  {
    id: 'boq-08',
    category: 'Subkontraktor Spesialis',
    itemDescription: 'Kaca Tempered 10mm & Kusen Alumunium Hitam Anodized',
    specification: 'Partisi kaca frameless board room + pivot swing glass door',
    unit: 'm2',
    volume: 48,
    unitPriceHPP: 850000,
    totalHPP: 40800000,
    markupPercent: 28,
    quotationPrice: 52224000,
  },
  {
    id: 'boq-09',
    category: 'Subkontraktor Spesialis',
    itemDescription: 'Solid Surface Acrylic Table Top Counter Pantry',
    specification: 'LG Hausys HI-MACS seamless jointing tebal 12mm',
    unit: 'm1',
    volume: 14,
    unitPriceHPP: 1650000,
    totalHPP: 23100000,
    markupPercent: 28,
    quotationPrice: 29568000,
  },
  // Overhead & Operasional
  {
    id: 'boq-10',
    category: 'Overhead & Operasional',
    itemDescription: 'Mobilisasi, Demobilisasi & Sewa Armada Truk Workshop-Site',
    specification: 'Truk Colt Diesel Double (3x Pengiriman pulang-pergi)',
    unit: 'Trip',
    volume: 6,
    unitPriceHPP: 1200000,
    totalHPP: 7200000,
    markupPercent: 20,
    quotationPrice: 8640000,
  },
  {
    id: 'boq-11',
    category: 'Overhead & Operasional',
    itemDescription: 'Proteksi Lapangan (Plastik Cor, Bubble wrap, Corrugated paper)',
    specification: 'Proteksi lantai gedung SCBD & lift barang protokol tenant',
    unit: 'Lot',
    volume: 1,
    unitPriceHPP: 4500000,
    totalHPP: 4500000,
    markupPercent: 20,
    quotationPrice: 5400000,
  },
];

export const initialExpenses: CostExpense[] = [
  {
    id: 'exp-01',
    projectId: 'prj-001',
    projectName: 'Fit-out Kantor FinTech Nexus SCBD',
    date: '2026-09-24',
    category: 'Material',
    description: 'Pembelian HPL Taco Walnut Tambahan (15 Lbr)',
    vendorOrRecipient: 'CV Sumber Kayu Mandiri',
    budgetAllocated: 3225000,
    actualAmount: 3450000,
    variance: -225000,
    status: 'Flagged Overbudget',
    receiptNo: 'INV/SKM/2026/0924',
    paymentMethod: 'Transfer Bank',
  },
  {
    id: 'exp-02',
    projectId: 'prj-001',
    projectName: 'Fit-out Kantor FinTech Nexus SCBD',
    date: '2026-09-22',
    category: 'Upah Tukang',
    description: 'Upah Mingguan 8 Tukang Setting Site (Minggu ke-7)',
    vendorOrRecipient: 'Mandor Suparno',
    budgetAllocated: 12500000,
    actualAmount: 12200000,
    variance: 300000,
    status: 'Approved',
    receiptNo: 'KWT/TKG-SCBD/W7',
    paymentMethod: 'Transfer Bank',
  },
  {
    id: 'exp-03',
    projectId: 'prj-001',
    projectName: 'Fit-out Kantor FinTech Nexus SCBD',
    date: '2026-09-20',
    category: 'Subkontraktor',
    description: 'DP 50% Partisi Kaca Tempered Curved 10mm',
    vendorOrRecipient: 'PT Asahi Kaca Megah',
    budgetAllocated: 20400000,
    actualAmount: 20400000,
    variance: 0,
    status: 'Approved',
    receiptNo: 'INV/AKM/2026/088',
    paymentMethod: 'Transfer Bank',
  },
  {
    id: 'exp-04',
    projectId: 'prj-002',
    projectName: 'Tanamera Cafe & Roastery Senopati',
    date: '2026-09-18',
    category: 'Material',
    description: 'Marmer Carrara Slab Khusus Bar Counter (Import)',
    vendorOrRecipient: 'PT Granit Indah Perkasa',
    budgetAllocated: 24000000,
    actualAmount: 26800000,
    variance: -2800000,
    status: 'Flagged Overbudget',
    receiptNo: 'INV/GIP/MRM-112',
    paymentMethod: 'Transfer Bank',
  },
  {
    id: 'exp-05',
    projectId: 'prj-002',
    projectName: 'Tanamera Cafe & Roastery Senopati',
    date: '2026-09-15',
    category: 'Overhead',
    description: 'Sewa Izin Bongkar Malam & Uang Kebersihan DLH',
    vendorOrRecipient: 'Pengelola Lingkungan Senopati',
    budgetAllocated: 2500000,
    actualAmount: 2200000,
    variance: 300000,
    status: 'Approved',
    receiptNo: 'KWT/IZIN-092',
    paymentMethod: 'Kas Lapangan (Petty Cash)',
  },
  {
    id: 'exp-06',
    projectId: 'prj-003',
    projectName: 'Penthouse Kemang Village Residence',
    date: '2026-09-12',
    category: 'Material',
    description: 'Bahan Multipleks 18mm & Veneer Walnut Lot 1',
    vendorOrRecipient: 'CV Sumber Kayu Mandiri',
    budgetAllocated: 45000000,
    actualAmount: 43500000,
    variance: 1500000,
    status: 'Approved',
    receiptNo: 'INV/SKM/VN-041',
    paymentMethod: 'Transfer Bank',
  },
];

export const initialWorkers: Worker[] = [
  {
    id: 'wk-01',
    name: 'Suparno (Mandor)',
    specialty: 'Mandor Kayu',
    dailyRate: 260000,
    status: 'Aktif di Site',
    currentProject: 'Fit-out Kantor FinTech Nexus SCBD',
    phone: '0812-4411-9988',
    rating: 4.9,
  },
  {
    id: 'wk-02',
    name: 'Wahyudi',
    specialty: 'Tukang HPL',
    dailyRate: 220000,
    status: 'Aktif di Site',
    currentProject: 'Fit-out Kantor FinTech Nexus SCBD',
    phone: '0813-2211-5501',
    rating: 4.8,
  },
  {
    id: 'wk-03',
    name: 'Sutrisno',
    specialty: 'Tukang Duco / Finishing',
    dailyRate: 240000,
    status: 'Workshop Cibubur',
    currentProject: 'Penthouse Kemang Village Residence',
    phone: '0857-1199-3322',
    rating: 4.9,
  },
  {
    id: 'wk-04',
    name: 'Rahmat Hidayat',
    specialty: 'Teknisi MEP & Listrik',
    dailyRate: 230000,
    status: 'Aktif di Site',
    currentProject: 'Tanamera Cafe & Roastery Senopati',
    phone: '0819-0909-1122',
    rating: 4.7,
  },
  {
    id: 'wk-05',
    name: 'Agus Triono',
    specialty: 'Tukang Plafon & Partisi',
    dailyRate: 210000,
    status: 'Standby',
    currentProject: 'Standby Workshop',
    phone: '0812-9988-1234',
    rating: 4.6,
  },
  {
    id: 'wk-06',
    name: 'Doni Saputra',
    specialty: 'Helper Lapangan',
    dailyRate: 160000,
    status: 'Aktif di Site',
    currentProject: 'Fit-out Kantor FinTech Nexus SCBD',
    phone: '0856-7788-9900',
    rating: 4.5,
  },
];

export const initialVendors: Vendor[] = [
  {
    id: 'vd-01',
    name: 'CV Sumber Kayu Mandiri',
    category: 'HPL & Wood Sheet',
    contactPerson: 'Ko Ahok (Owner)',
    phone: '0811-1029-338',
    city: 'Jakarta Timur (Cipinang)',
    activeOrders: 3,
    rating: 4.9,
    paymentTerm: 'Tempo 30 Hari',
  },
  {
    id: 'vd-02',
    name: 'PT Asahi Kaca Megah',
    category: 'Kaca & Alumunium',
    contactPerson: 'Bpk. Surya Dinata',
    phone: '0812-9900-2211',
    city: 'Jakarta Barat (Daan Mogot)',
    activeOrders: 1,
    rating: 4.8,
    paymentTerm: 'Tempo 14 Hari',
  },
  {
    id: 'vd-03',
    name: 'PT Granit Indah Perkasa',
    category: 'Solid Surface & Marmer',
    contactPerson: 'Ibu Veronica',
    phone: '0813-8822-4411',
    city: 'Tangerang',
    activeOrders: 2,
    rating: 4.6,
    paymentTerm: 'COD',
  },
  {
    id: 'vd-04',
    name: 'Mitra Hardware Hardware & Blum',
    category: 'Hardware & Fitting',
    contactPerson: 'Yanto',
    phone: '0812-7711-4433',
    city: 'Glodok Jakarta Barat',
    activeOrders: 1,
    rating: 4.9,
    paymentTerm: 'Tempo 30 Hari',
  },
];

export const initialPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-01',
    poNumber: 'PO-SRA-2026/09-001',
    projectId: 'prj-001',
    projectName: 'Fit-out Kantor FinTech Nexus SCBD',
    vendorName: 'CV Sumber Kayu Mandiri',
    itemsSummary: 'Multipleks 18mm Uty (50 Lbr), Lem Aica (10 Kaleng)',
    totalAmount: 15900000,
    requestDate: '2026-09-20',
    deliveryDate: '2026-09-22',
    status: 'Diterima Lapangan',
    picRequest: 'Rian Pratama',
  },
  {
    id: 'po-02',
    poNumber: 'PO-SRA-2026/09-002',
    projectId: 'prj-001',
    projectName: 'Fit-out Kantor FinTech Nexus SCBD',
    vendorName: 'PT Asahi Kaca Megah',
    itemsSummary: 'Kaca Tempered 10mm Frameless (48 m2) & Pivot Door Hinge',
    totalAmount: 40800000,
    requestDate: '2026-09-23',
    deliveryDate: '2026-09-30',
    status: 'Sedang Dikirim',
    picRequest: 'Budi Santoso',
  },
  {
    id: 'po-03',
    poNumber: 'PO-SRA-2026/09-003',
    projectId: 'prj-003',
    projectName: 'Penthouse Kemang Village Residence',
    vendorName: 'Mitra Hardware Hardware & Blum',
    itemsSummary: 'Blum Clip Top Blumotion 110 deg (64 set) + Push Open TIP-ON',
    totalAmount: 9280000,
    requestDate: '2026-09-25',
    deliveryDate: '2026-10-02',
    status: 'Disetujui',
    picRequest: 'Agus Salim',
  },
  {
    id: 'po-04',
    poNumber: 'PO-SRA-2026/09-004',
    projectId: 'prj-002',
    projectName: 'Tanamera Cafe & Roastery Senopati',
    vendorName: 'PT Granit Indah Perkasa',
    itemsSummary: 'Tambahan slab Marmer Carrara 20mm Polish Bevel',
    totalAmount: 7500000,
    requestDate: '2026-09-27',
    deliveryDate: '2026-10-01',
    status: 'Pending Approval',
    picRequest: 'Hendra Gunawan',
  },
];

export const initialTermins: PaymentTermin[] = [
  {
    id: 'tmn-01',
    projectId: 'prj-001',
    projectName: 'Fit-out Kantor FinTech Nexus SCBD',
    clientName: 'PT Nexus Finansial Digital',
    terminName: 'DP 30%',
    percentage: 30,
    amount: 435000000,
    triggerCondition: 'Penandatanganan Kontrak & SPK',
    dueDate: '2026-08-05',
    paidDate: '2026-08-04',
    status: 'Lunas',
    invoiceNumber: 'INV/SRA/2026/08-001',
  },
  {
    id: 'tmn-02',
    projectId: 'prj-001',
    projectName: 'Fit-out Kantor FinTech Nexus SCBD',
    clientName: 'PT Nexus Finansial Digital',
    terminName: 'Termin 1 (30%)',
    percentage: 30,
    amount: 435000000,
    triggerCondition: 'Progress Fisik Lapangan 40% (MEP & Rangka Siap)',
    dueDate: '2026-09-05',
    paidDate: '2026-09-03',
    status: 'Lunas',
    invoiceNumber: 'INV/SRA/2026/09-004',
  },
  {
    id: 'tmn-03',
    projectId: 'prj-001',
    projectName: 'Fit-out Kantor FinTech Nexus SCBD',
    clientName: 'PT Nexus Finansial Digital',
    terminName: 'Termin 2 (30%)',
    percentage: 30,
    amount: 435000000,
    triggerCondition: 'Progress Fisik 75% (Cabinet Masuk & Pemasangan Kaca)',
    dueDate: '2026-10-01',
    status: 'Menunggu Pembayaran',
    invoiceNumber: 'INV/SRA/2026/09-012',
  },
  {
    id: 'tmn-04',
    projectId: 'prj-001',
    projectName: 'Fit-out Kantor FinTech Nexus SCBD',
    clientName: 'PT Nexus Finansial Digital',
    terminName: 'Retensi 10%',
    percentage: 10,
    amount: 145000000,
    triggerCondition: 'Serah Terima Pertama (BAST 1) + Garansi Pemeliharaan 60 Hari',
    dueDate: '2026-12-15',
    status: 'Draft / Belum Ditagihkan',
    invoiceNumber: 'DRAFT-RETENSI-SCBD',
  },
  {
    id: 'tmn-05',
    projectId: 'prj-002',
    projectName: 'Tanamera Cafe & Roastery Senopati',
    clientName: 'Tanamera Hospitality Group',
    terminName: 'Termin 2 (30%)',
    percentage: 30,
    amount: 246000000,
    triggerCondition: 'Progress Fisik 80% (Bar Counter & Flooring Selesai)',
    dueDate: '2026-09-20',
    status: 'Jatuh Tempo',
    invoiceNumber: 'INV/SRA/2026/09-008',
  },
  {
    id: 'tmn-06',
    projectId: 'prj-003',
    projectName: 'Penthouse Kemang Village Residence',
    clientName: 'Private Residence (Mr. Ronald)',
    terminName: 'DP 40%',
    percentage: 40,
    amount: 752000000,
    triggerCondition: 'Penandatanganan SPK & Pengadaan Bahan Kayu',
    dueDate: '2026-08-20',
    paidDate: '2026-08-19',
    status: 'Lunas',
    invoiceNumber: 'INV/SRA/2026/08-015',
  },
];

export const initialSitePhotos: SitePhoto[] = [
  {
    id: 'sp-01',
    projectId: 'prj-001',
    area: 'Area Kerja Open Plan & Baffle Ceiling',
    caption: 'Pemasangan acoustic ceiling baffle metal strip dan framing kaca tempered curved radius 1.2m',
    date: '2026-09-27',
    uploader: 'Rian Pratama (Site Supervisor)',
    imageUrl: '/images/project-office.jpg',
    type: 'Dalam Proses',
  },
  {
    id: 'sp-02',
    projectId: 'prj-002',
    area: 'Barista Counter & Ambient Wall',
    caption: 'Mockup & dry assembly custom fluted oak bar counter dengan brass shelving & marble top',
    date: '2026-09-26',
    uploader: 'Hendra Gunawan (Site Supervisor)',
    imageUrl: '/images/project-cafe.jpg',
    type: 'Selesai',
  },
  {
    id: 'sp-03',
    projectId: 'prj-003',
    area: 'Workshop Joinery Cibubur',
    caption: 'Pekerjaan profilisasi kayu walnut solid dan perakitan drawer walk-in closet dengan mesin Altendorf',
    date: '2026-09-25',
    uploader: 'Agus Salim (Workshop Manager)',
    imageUrl: '/images/project-workshop.jpg',
    type: 'Dalam Proses',
  },
];

export const initialDailyReports: DailyReport[] = [
  {
    id: 'dr-01',
    projectId: 'prj-001',
    date: '2026-09-27',
    weather: 'Cerah',
    tukangCount: 14,
    pic: 'Rian Pratama (Pengawas Lapangan)',
    summary: 'Melanjutkan instalasi partisi kaca frameless curved lantai 24. Pemasangan panel kisi-kisi kayu di ruang board room. Tim MEP tes continuity kabel data LAN server.',
    materialsReceived: 'Kaca tempered 10mm 6 panel, Silicone sealant Dow Corning 12 tube.',
    obstacles: 'Akses lift barang gedung SCBD sempat antri 45 menit pada jam 14.00 karena maintenance chiller gedung.',
  },
  {
    id: 'dr-02',
    projectId: 'prj-002',
    date: '2026-09-27',
    weather: 'Mendung',
    tukangCount: 8,
    pic: 'Hendra Gunawan (Pengawas Lapangan)',
    summary: 'Pengecatan touchup dinding semen ekspos. Testing aliran drainase grease trap bar counter dan colokan mesin espresso 32A.',
    materialsReceived: 'Cat Nippon Momento 2 galon, Brass polish compound.',
    obstacles: 'Tidak ada kendala berarti. Rencana serah terima parsial hari Selasa depan.',
  },
];
